### ISSUE TITLE
Running Juicer+AutoHiC on Haploid Tiliqua HiFiasm assembly 

### ISSUE THREAD

**Issue by kiratalreja3** [kango2/ausarg#4]
- Running Juicer and 3D-DNA pipeline on haploid tiliqua hifiasm assembly as a test for juicer as well as AutoHiC

Observations 

- Whole process likely needs 96 hour walltime due to poor (or nature of processes) optimisation
- AutoHiC can be run separately after running juicer, but that's not the intended way to run it : the result is a .assembly file which needs to be fed back into 3d dna for a final result (AutoHiC took about an hour to finish in this mode)
- If AutoHiC is run as a whole, it will be much better - but it would likely need 96 hours
- Juicer and 3D Dna use only 10 cores efficiently

**Comment by kiratalreja3** [comment]
Update : Terrible results since the job was not run in diploid mode. AutoHiC failed, and no meanginful results obtained from the workflow. Closing the issue.

**Comment by dnazerg999** [comment]
Hi, I am the developer of AutoHiC. Can you send me the bug of it or why it failed with your data? We can fix it in next version.

**Comment by Jwindler** [comment]
> * Running Juicer and 3D-DNA pipeline on haploid tiliqua hifiasm assembly as a test for juicer as well as AutoHiC
> 
> Observations
> 
> * Whole process likely needs 96 hour walltime due to poor (or nature of processes) optimisation
> * AutoHiC can be run separately after running juicer, but that's not the intended way to run it : the result is a .assembly file which needs to be fed back into 3d dna for a final result (AutoHiC took about an hour to finish in this mode)
> * If AutoHiC is run as a whole, it will be much better - but it would likely need 96 hours
> * Juicer and 3D Dna use only 10 cores efficiently

The run time of 3d-dna depends not only on the thread used, but also on the input genome file format modified in AutoHiC. Therefore, it is recommended to use AutoHiC for the entire process. In addition, users who have already run 3d-dna can use AutoHiC to detect errors and obtain the modified assembly file to correct the genome.

**Comment by Jwindler** [comment]
> Update : Terrible results since the job was not run in diploid mode. AutoHiC failed, and no meanginful results obtained from the workflow. Closing the issue.

It is not necessary to specify whether it is in diploid mode when running AutoHiC. Can you please post your situation in detail?

**Comment by kiratalreja3** [comment]
Hi @Jwindler, can I connect with you over Slack/email to discuss this and share the results? Thanks for responding!

**Comment by Jwindler** [comment]
> Hi @Jwindler, can I connect with you over Slack/email to discuss this and share the results? Thanks for responding!

This is my email address: jzjlab@163.com
